import type { Metadata, Viewport } from 'next';
import { Figtree } from 'next/font/google'; // Example font, adjust as needed
import './globals.css'; // Assumes globals.css will be in the same dir in generated site (src/app/)
import { Analytics } from '@vercel/analytics/next';

const figtree = Figtree({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-figtree', // Ensure your Tailwind config can use this
});

export const metadata: Metadata = {
  title: 'My New Website', // This will likely be overridden by repoName in create-site API
  description: 'Generated by WebGo',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  themeColor: 'black', // Example, adjust or remove as needed
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={`${figtree.variable} font-sans`}> {/* Ensure font-sans is defined in your globals/tailwind */} 
        {children}
        <Analytics />
      </body>
    </html>
  );
} 